/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/basketball.glb public/models/bike.glb public/models/books.glb public/models/chopper.glb public/models/computer.glb public/models/shoes.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Basketball(props) {
  const { nodes, materials } = useGLTF("models/basketball.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BasketballBall.geometry}
        material={materials.Basketball}
      />
      <mesh
        geometry={nodes.BasketballBall_1.geometry}
        material={materials.BasketBallLines}
      />
    </group>
  );
}

useGLTF.preload("models/basketball.glb");
