/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/bike.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Bike(props) {
  const { nodes, materials } = useGLTF("models/bike.glb");
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload("models/bike.glb");
