/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/books.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Books(props) {
  const { nodes, materials } = useGLTF("models/books.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube017.geometry} material={materials.OffWhite} />
      <mesh geometry={nodes.Cube017_1.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube017_2.geometry} material={materials.BabyBlue} />
      <mesh geometry={nodes.Cube017_3.geometry} material={materials.Yellow} />
    </group>
  );
}

useGLTF.preload("models/books.glb");
