/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/chopper.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Chopper(props) {
  const { nodes, materials } = useGLTF("models/chopper.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.OffWhite} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials.Tan} />
      <mesh geometry={nodes.Cube001_5.geometry} material={materials.Yellow} />
    </group>
  );
}

useGLTF.preload("models/chopper.glb");
