/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/shoes.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Shoes(props) {
  const { nodes, materials } = useGLTF("models/shoes.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube011.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube011_1.geometry} material={materials.OffWhite} />
      <mesh geometry={nodes.Cube011_2.geometry} material={materials.BabyBlue} />
    </group>
  );
}

useGLTF.preload("models/shoes.glb");
