/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/bike.glb 
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Bike(props) {
  const { nodes, materials } = useGLTF("/models/bike.glb");
  const ref = useRef();
  const tl = useRef();
  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    tl.current.to(
      ref.current.rotation,
      {
        duration: 2,
        y: 1.5,
      },
      0
    );
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0.068, 0.073, 0.073]}
      >
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cube007_3.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube007_4.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube007_5.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cube007_6.geometry}
          material={materials["Material.006"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/bike.glb");
