/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Scene.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { animated, useSpring } from "@react-spring/three";

export function Scene(props) {
  const sceneRotation = useSpring({
    from: { sceneRotation: 0 },
    to: [
      {
        sceneRotation: -Math.PI / 2,
      },
      {
        sceneRotation: -Math.PI,
      },
      { sceneRotation: -1.5 * Math.PI },
      { sceneRotation: -2 * Math.PI },
    ],
    config: {
      mass: 5,
      tension: 400,
      friction: 50,
    },
    loop: true,
    immediate: true,
  });

  const { nodes, materials } = useGLTF("/models/Scene.glb");
  return (
    <group {...props} dispose={null}>
      <animated.group rotation={[0, 0, 0]} scale={[0.8, 1, 0.8]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials["Basketball.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Pink.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Gray.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_3.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_4.geometry}
          material={materials["OffWhite.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_5.geometry}
          material={materials["RedSmooth.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_6.geometry}
          material={materials["Tan.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_7.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_8.geometry}
          material={materials["BasketBallLines.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_9.geometry}
          material={materials.GreenDark}
        />
        <mesh
          geometry={nodes.Cylinder001_10.geometry}
          material={materials["BabyBlue.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_11.geometry}
          material={materials["Oil.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_12.geometry}
          material={materials["Yellow.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_13.geometry}
          material={materials["RedLigth.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_14.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cylinder001_15.geometry}
          material={materials["Green.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_16.geometry}
          material={materials["Material.005"]}
        />
      </animated.group>
    </group>
  );
}

useGLTF.preload("/models/Scene.glb");
