/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Scene.glb 
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Test(props) {
  const { nodes, materials } = useGLTF("/models/Scene.glb");

  const ref = useRef();
  const tl = useRef();
  tl.current = 0;
  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });
  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // VERTICAL ANIMATION
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -1,
      },
      0
    );
  }, []);
  return (
    <group {...props} dispose={null} ref={ref}>
      <group scale={[0.919, 1, 0.919]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials["Basketball.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Pink.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Gray.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_3.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_4.geometry}
          material={materials["OffWhite.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_5.geometry}
          material={materials["RedSmooth.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_6.geometry}
          material={materials["Tan.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_7.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_8.geometry}
          material={materials["BasketBallLines.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_9.geometry}
          material={materials.GreenDark}
        />
        <mesh
          geometry={nodes.Cylinder001_10.geometry}
          material={materials["BabyBlue.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_11.geometry}
          material={materials["Oil.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_12.geometry}
          material={materials["Yellow.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_13.geometry}
          material={materials["RedLigth.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_14.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cylinder001_15.geometry}
          material={materials["Green.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_16.geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Scene.glb");
