/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/books.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Books(props) {
  const { nodes, materials } = useGLTF("models/books.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation-y={Math.PI / 2}
      scale={5}
      position={[1, -8.2, 0]}
    >
      <mesh geometry={nodes.Cube012.geometry} material={materials.Basketball} />
      <mesh geometry={nodes.Cube012_1.geometry} material={materials.OffWhite} />
      <mesh geometry={nodes.Cube012_2.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube012_3.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Cube012_4.geometry} material={materials.BabyBlue} />
    </group>
  );
}

useGLTF.preload("models/books.glb");
