/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/books.glb 
*/

import React from "react";
import { Outlines, useGLTF } from "@react-three/drei";

export function Books(props) {
  const { nodes, materials } = useGLTF("models/books.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[Math.PI / 6, Math.PI / 2, 0]}
      scale={5}
      position={[1, -8.2, 0]}
    >
      <mesh geometry={nodes.Cube012.geometry} material={materials.Basketball}>
        <Outlines thickness={0.01} color="black" />
      </mesh>
      <mesh geometry={nodes.Cube012_1.geometry} material={materials.OffWhite}>
        <Outlines thickness={0.01} color="black" />
      </mesh>
      <mesh geometry={nodes.Cube012_2.geometry} material={materials.Black}>
        <Outlines thickness={0.01} color="black" />
      </mesh>
      <mesh geometry={nodes.Cube012_3.geometry} material={materials.Yellow}>
        <Outlines thickness={0.01} color="black" />
      </mesh>
      <mesh geometry={nodes.Cube012_4.geometry} material={materials.BabyBlue}>
        <Outlines thickness={0.01} color="black" />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/books.glb");
