/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/computer.glb 
Author: Tobalation (https://sketchfab.com/tobalation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-3a496376915846459d77fc14fdd6c1e0
Title: Retro computer
*/

import React from "react";
import { Outlines, useGLTF } from "@react-three/drei";

export function Computer(props) {
  const isMobile = window.screen.width < 768;
  const { nodes, materials } = useGLTF("models/computer.glb");
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={isMobile ? 0.9 : 1.4}
        position={isMobile ? [1, -6, 0] : [4.4, -7, 0]}
      >
        <group rotation={[Math.PI / 1.5, -Math.PI / 3, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.TextureGrid}
            position={[0, 0, 0]}
            rotation={[0.087, 0, 0]}
          >
            <Outlines thickness={0.05} color="black" />
          </mesh>
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.TextureGrid}
            position={[0, 0.5, 0.031]}
            rotation={[0.087, 0, 0]}
          >
            <Outlines thickness={0.05} color="black" />
          </mesh>
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.TextureGrid}
            position={[0.875, 0.063, 0.75]}
            rotation={[0.087, 0, 0]}
          >
            <Outlines thickness={0.05} color="black" />
          </mesh>
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.TextureGrid}
            position={[0, 0.062, 0.813]}
            rotation={[0.087, 0, 0]}
          >
            <Outlines thickness={0.05} color="black" />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/computer.glb");
