/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/thinker.glb 
*/

import React from "react";
import { Outlines, useGLTF } from "@react-three/drei";

export function Thinker(props) {
  const isMobile = window.screen.width < 768;
  const { nodes, materials } = useGLTF("models/thinker.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={isMobile ? 0.02 : 0.038}
      position={
        isMobile ? [-1, (-6 * window.screen.height) / 600, -3] : [-5, -8, 0]
      }
      rotation={[0, Math.PI / 8, 0]}
    >
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      >
        <Outlines thickness={2} color="black" />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/thinker.glb");
