/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/thinker.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Thinker(props) {
  const { nodes, materials } = useGLTF("models/thinker.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={[0.025, 0.025, 0.025]}
      position={[-4, -9, 0]}
      rotation={[0, Math.PI / 8, 0]}
    >
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
    </group>
  );
}

useGLTF.preload("models/thinker.glb");
